apiVersion: v1
kind: deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: vishalthegreat/app:latest
        ports:
        - containerPort: 8080